name: DeployAndSoaking

on:
  push:
    branches:
      - master
    paths:
      - 'appointment-service/**'
  workflow_dispatch:

jobs:
  deploy-and-soak:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          cd appointment-service
          pip install -r requirements.txt
          
      - name: Start appointment service and run for 30 minutes
        run: |
          cd appointment-service
          echo "Starting appointment service with OpenTelemetry..."
          export OTEL_PYTHON_DISTRO=aws_distro
          export OTEL_TRACES_EXPORTER=none
          export OTEL_LOGS_EXPORTER=none
          export OTEL_METRICS_EXPORTER=awsemf
          export OTEL_PYTHON_CONFIGURATOR=aws_configurator
          export OTEL_EXPORTER_OTLP_LOGS_HEADERS=x-aws-log-group=hackathon-apm,x-aws-log-stream=default,x-aws-metric-namespace=hackathon-apm
          export OTEL_RESOURCE_ATTRIBUTES=service.name=AppointmentService,aws.log.group.names=hackathon-apm
          opentelemetry-instrument python app.py &
          SERVICE_PID=$!
          echo "Service started with PID: $SERVICE_PID"
          
          echo "Waiting for service to be ready..."
          sleep 10
          
          echo "Starting traffic generation..."
          (
            START_TIME=$(date +%s)
            END_TIME=$((START_TIME + 1800))  # 30 minutes = 1800 seconds
            i=1
            while [ $(date +%s) -lt $END_TIME ]; do
              curl -s -X POST http://localhost:5000/createAppointment \
                -H "Content-Type: application/json" \
                -d "{
                  \"patient_name\": \"Patient $i\",
                  \"doctor_name\": \"Dr. Test\",
                  \"appointment_date\": \"2024-01-25\",
                  \"appointment_time\": \"$((9 + i % 8)):00 AM\",
                  \"notes\": \"Test appointment $i - This is a very long note with lots of detailed information about the patient's medical history, symptoms, previous treatments, medications, allergies, family history, and other relevant medical data that could be quite extensive. The purpose is to simulate real-world scenarios where appointment notes can contain substantial amounts of text including detailed examination findings, treatment plans, follow-up instructions, medication adjustments, lifestyle recommendations, referral information, and comprehensive documentation that healthcare providers typically maintain for proper patient care continuity. This large text block will help demonstrate memory usage patterns and potential memory leak issues in the appointment service when storing substantial amounts of data for each appointment record in the system. Additional detailed medical information includes comprehensive patient assessment, vital signs monitoring, diagnostic test results, laboratory findings, imaging study interpretations, surgical procedure notes, post-operative care instructions, rehabilitation protocols, physical therapy recommendations, occupational therapy assessments, nutritional counseling notes, psychological evaluation findings, social work assessments, discharge planning documentation, insurance authorization details, billing and coding information, quality assurance metrics, patient satisfaction surveys, care coordination communications, interdisciplinary team meeting notes, family conferences documentation, advance directive discussions, pain management protocols, medication reconciliation records, allergy verification procedures, infection control measures, fall risk assessments, pressure ulcer prevention strategies, cognitive assessments, functional capacity evaluations, home health care arrangements, durable medical equipment prescriptions, follow-up appointment scheduling, specialist referral coordination, laboratory test ordering, radiology study requests, pharmacy consultations, case management reviews, utilization management assessments, peer review documentation, clinical pathway adherence monitoring, evidence-based practice implementation, continuing education requirements, professional development activities, research participation documentation, clinical trial enrollment considerations, biomedical ethics consultations, legal compliance verification, regulatory reporting requirements, accreditation preparation materials, performance improvement initiatives, patient safety event reporting, risk management assessments, emergency preparedness protocols, disaster response procedures, business continuity planning, technology integration strategies, electronic health record optimization, interoperability standards compliance, data security measures, privacy protection protocols, HIPAA compliance verification, audit preparation documentation, vendor management oversight, contract negotiation records, budget planning materials, resource allocation strategies, staffing optimization plans, workflow efficiency improvements, customer service excellence programs, community outreach initiatives, public health collaboration efforts, population health management strategies, preventive care coordination, chronic disease management protocols, wellness program development, health promotion activities, disease prevention strategies, screening program implementation, vaccination administration records, immunization status tracking, travel health consultations, occupational health assessments, environmental health evaluations, infectious disease surveillance, outbreak investigation procedures, contact tracing protocols, quarantine management guidelines, isolation precaution implementation, antimicrobial stewardship programs, healthcare-associated infection prevention, patient education materials development, family caregiver training programs, community resource identification, social determinants assessment, health equity initiatives, cultural competency training, language interpretation services, accessibility accommodation procedures, disability rights compliance, age-specific care considerations, pediatric assessment protocols, geriatric evaluation procedures, women's health screening programs, men's health promotion activities, LGBTQ+ inclusive care practices, trauma-informed care implementation, mental health integration strategies, substance abuse treatment coordination, addiction recovery support services, crisis intervention procedures, suicide prevention protocols, domestic violence screening, elder abuse detection, child protection reporting, mandated reporter training, ethical decision-making frameworks, informed consent procedures, shared decision-making processes, patient advocacy services, grievance resolution procedures, complaint investigation protocols, satisfaction improvement initiatives, service recovery programs, communication enhancement strategies, conflict resolution techniques, negotiation skills development, leadership training programs, team building activities, staff development initiatives, mentorship program coordination, succession planning strategies, retention improvement efforts, recruitment optimization procedures, onboarding process enhancement, performance evaluation systems, competency validation programs, credentialing maintenance requirements, license renewal procedures, certification tracking systems, continuing education coordination, professional membership management, conference attendance planning, knowledge sharing initiatives, best practice dissemination, innovation implementation strategies, change management procedures, organizational development activities, strategic planning processes, mission alignment verification, vision statement implementation, value proposition development, brand management strategies, marketing communication plans, public relations coordination, media interaction protocols, crisis communication procedures, stakeholder engagement activities, community partnership development, collaborative care agreements, service line expansion planning, market analysis studies, competitive intelligence gathering, financial performance monitoring, revenue cycle optimization, cost reduction initiatives, efficiency improvement projects, productivity enhancement strategies, quality improvement programs, patient outcome measurements, clinical indicator tracking, benchmark comparison studies, peer review processes, medical staff credentialing, privileging procedures, competency assessments, performance improvement requirements.\"
                }" > /dev/null
              i=$((i + 1))
              sleep 0.1
            done
          ) &
          TRAFFIC_PID=$!
          
          echo "Running soak test for 30 minutes..."
          sleep 1800  # 30 minutes = 1800 seconds
          
          echo "Stopping traffic generation and appointment service..."
          kill $TRAFFIC_PID 2>/dev/null || true
          kill $SERVICE_PID
          echo "Soak test completed successfully"